"""
Demo data for AnubhavAI — used when OPENAI_API_KEY is not set.
All responses are deterministic and seeded, covering all 3 languages.
"""
from typing import Dict, Any

DEMO_SCENARIO = {
    "en": {
        "raw_text": "I have been making and selling homemade pickles for five years. I manage customers, purchase ingredients, calculate prices, and also handle packaging.",
        "summary": "Five years of experience in home-based food production and small business management, including sales, customer handling, ingredient sourcing, pricing, and packaging.",
    },
    "hi": {
        "raw_text": "मैं पाँच साल से घर पर अचार बनाकर बेच रही हूँ। मैं ग्राहकों को संभालती हूँ, सामग्री खरीदती हूँ, कीमतें तय करती हूँ और पैकेजिंग भी करती हूँ।",
        "summary": "पाँच वर्षों का घरेलू खाद्य उत्पादन और लघु व्यवसाय प्रबंधन का अनुभव, जिसमें बिक्री, ग्राहक प्रबंधन, कच्चे माल की खरीद, मूल्य निर्धारण और पैकेजिंग शामिल है।",
    },
    "ta": {
        "raw_text": "நான் ஐந்து ஆண்டுகளாக வீட்டில் ஊறுகாய் தயாரித்து விற்று வருகிறேன். வாடிக்கையாளர்களை நிர்வகிக்கிறேன், பொருட்கள் வாங்குகிறேன், விலை கணக்கிடுகிறேன் மற்றும் பேக்கேஜிங் செய்கிறேன்.",
        "summary": "ஐந்து ஆண்டுகால வீட்டு உணவு உற்பத்தி மற்றும் சிறு வணிக நிர்வாக அனுபவம், இதில் விற்பனை, வாடிக்கையாளர் சேவை, மூலப்பொருள் கொள்முதல், விலை நிர்ணயம் மற்றும் பேக்கேஜிங் அடங்கும்.",
    },
}

DEMO_SKILLS = [
    {
        "id": 1,
        "name": "Food Production",
        "name_hi": "खाद्य उत्पादन",
        "name_ta": "உணவு உற்பத்தி",
        "category": "Food Production",
        "confidence": 0.95,
        "confidence_level": "high",
        "evidence": {
            "en": "User has been making homemade pickles for five years — consistent, long-term food production experience.",
            "hi": "उपयोगकर्ता पाँच वर्षों से घर पर अचार बना रही हैं — यह लगातार, दीर्घकालिक खाद्य उत्पादन अनुभव दर्शाता है।",
            "ta": "பயனர் ஐந்து ஆண்டுகளாக வீட்டில் ஊறுகாய் தயாரிக்கிறார் — இது நிலையான, நீண்டகால உணவு உற்பத்தி அனுபவத்தை காட்டுகிறது.",
        },
        "years_experience": 5,
    },
    {
        "id": 2,
        "name": "Sales",
        "name_hi": "बिक्री",
        "name_ta": "விற்பனை",
        "category": "Sales",
        "confidence": 0.90,
        "confidence_level": "high",
        "evidence": {
            "en": "User sells products directly to customers, indicating active sales experience.",
            "hi": "उपयोगकर्ता सीधे ग्राहकों को उत्पाद बेचती हैं, जो सक्रिय बिक्री अनुभव दर्शाता है।",
            "ta": "பயனர் நேரடியாக வாடிக்கையாளர்களுக்கு பொருட்களை விற்கிறார், இது செயலில் உள்ள விற்பனை அனுபவத்தை காட்டுகிறது.",
        },
        "years_experience": 5,
    },
    {
        "id": 3,
        "name": "Customer Handling",
        "name_hi": "ग्राहक प्रबंधन",
        "name_ta": "வாடிக்கையாளர் சேவை",
        "category": "Customer Handling",
        "confidence": 0.88,
        "confidence_level": "high",
        "evidence": {
            "en": "User manages customer relationships directly, including handling queries and repeat orders.",
            "hi": "उपयोगकर्ता सीधे ग्राहक संबंध प्रबंधित करती हैं, जिसमें पूछताछ और दोहराए जाने वाले ऑर्डर शामिल हैं।",
            "ta": "பயனர் வாடிக்கையாளர் உறவுகளை நேரடியாக நிர்வகிக்கிறார், இதில் கேள்விகள் மற்றும் மீண்டும் மீண்டும் வரும் ஆர்டர்களை கையாளுவது அடங்கும்.",
        },
        "years_experience": 5,
    },
    {
        "id": 4,
        "name": "Inventory Management",
        "name_hi": "इन्वेंटरी प्रबंधन",
        "name_ta": "சரக்கு மேலாண்மை",
        "category": "Inventory",
        "confidence": 0.72,
        "confidence_level": "medium",
        "evidence": {
            "en": "User purchases ingredients regularly, indicating inventory tracking and procurement skills.",
            "hi": "उपयोगकर्ता नियमित रूप से सामग्री खरीदती हैं, जो इन्वेंटरी ट्रैकिंग और खरीद कौशल दर्शाता है।",
            "ta": "பயனர் தொடர்ந்து மூலப்பொருட்களை வாங்குகிறார், இது சரக்கு கண்காணிப்பு மற்றும் கொள்முதல் திறன்களை காட்டுகிறது.",
        },
        "years_experience": 5,
    },
    {
        "id": 5,
        "name": "Pricing & Marketing",
        "name_hi": "मूल्य निर्धारण और विपणन",
        "name_ta": "விலை நிர்ணயம் மற்றும் சந்தைப்படுத்தல்",
        "category": "Business Management",
        "confidence": 0.75,
        "confidence_level": "medium",
        "evidence": {
            "en": "User calculates prices independently, showing basic business acumen and pricing strategy skills.",
            "hi": "उपयोगकर्ता स्वतंत्र रूप से कीमतें तय करती हैं, जो बुनियादी व्यापारिक कुशलता और मूल्य निर्धारण रणनीति कौशल दर्शाता है।",
            "ta": "பயனர் சுயாதீனமாக விலைகளை கணக்கிடுகிறார், இது அடிப்படை வணிக புத்திசாலித்தனம் மற்றும் விலை நிர்ணய திறன்களை காட்டுகிறது.",
        },
        "years_experience": 5,
    },
    {
        "id": 6,
        "name": "Small Business Management",
        "name_hi": "लघु व्यवसाय प्रबंधन",
        "name_ta": "சிறு வணிக நிர்வாகம்",
        "category": "Business Management",
        "confidence": 0.80,
        "confidence_level": "medium",
        "evidence": {
            "en": "End-to-end management of a home-based pickle business demonstrates small business management capability.",
            "hi": "घरेलू अचार व्यवसाय का शुरू से अंत तक प्रबंधन लघु व्यवसाय प्रबंधन क्षमता दर्शाता है।",
            "ta": "வீட்டு அடிப்படையிலான ஊறுகாய் வணிகத்தின் தொடக்கம் முதல் இறுதிவரை நிர்வாகம் சிறு வணிக மேலாண்மை திறனை நிரூபிக்கிறது.",
        },
        "years_experience": 5,
    },
]

DEMO_VERIFICATION = {
    "skill_name": {
        "en": "Customer Handling",
        "hi": "ग्राहक प्रबंधन",
        "ta": "வாடிக்கையாளர் சேவை",
    },
    "scenario": {
        "en": "A customer says the product they purchased yesterday is damaged and asks for a refund. The customer is upset and speaking loudly.",
        "hi": "एक ग्राहक कह रहा है कि कल खरीदा गया उत्पाद क्षतिग्रस्त है और वापसी की मांग कर रहा है। ग्राहक परेशान है और जोर से बोल रहा है।",
        "ta": "ஒரு வாடிக்கையாளர் நேற்று வாங்கிய பொருள் சேதமடைந்ததாகக் கூறி பணத்தைத் திரும்பக் கேட்கிறார். வாடிக்கையாளர் கோபமாக உரக்கப் பேசுகிறார்.",
    },
    "question": {
        "en": "What would you do in this situation? Please explain how you would handle this customer.",
        "hi": "इस स्थिति में आप क्या करेंगे? कृपया बताएं कि आप इस ग्राहक को कैसे संभालेंगे।",
        "ta": "இந்த சூழ்நிலையில் நீங்கள் என்ன செய்வீர்கள்? இந்த வாடிக்கையாளரை எவ்வாறு கையாளுவீர்கள் என்று விளக்குங்கள்.",
    },
    "result": {
        "status": "demonstrated",
        "score": 88,
        "dimensions": {
            "Problem Understanding": 92,
            "Communication": 88,
            "Decision Making": 85,
            "Empathy": 90,
        },
        "explanation": {
            "en": "You handled the customer concern professionally and showed good problem-solving skills. You demonstrated empathy, clear communication, and a practical approach to resolving the issue.",
            "hi": "आपने ग्राहक की समस्या को पेशेवर तरीके से संभाला और अच्छी समस्या-समाधान कौशल दिखाई। आपने सहानुभूति, स्पष्ट संचार और समस्या को हल करने का व्यावहारिक दृष्टिकोण प्रदर्शित किया।",
            "ta": "வாடிக்கையாளரின் கவலையை நீங்கள் தொழில்முறையாக கையாண்டீர்கள், மேலும் சிறந்த சிக்கல் தீர்க்கும் திறன்களை நிரூபித்தீர்கள். அனுதாபம், தெளிவான தகவல் தொடர்பு மற்றும் சிக்கலை தீர்க்கும் நடைமுறை அணுகுமுறை ஆகியவற்றை நீங்கள் காட்டினீர்கள்.",
        },
    },
}

DEMO_SKILL_GAPS = [
    {
        "skill_name": {"en": "Sales", "hi": "बिक्री", "ta": "விற்பனை"},
        "current_score": 90,
        "target_score": 100,
    },
    {
        "skill_name": {"en": "Customer Handling", "hi": "ग्राहक प्रबंधन", "ta": "வாடிக்கையாளர் சேவை"},
        "current_score": 85,
        "target_score": 100,
    },
    {
        "skill_name": {"en": "Food Production", "hi": "खाद्य उत्पादन", "ta": "உணவு உற்பத்தி"},
        "current_score": 75,
        "target_score": 100,
    },
    {
        "skill_name": {"en": "Inventory Management", "hi": "इन्वेंटरी प्रबंधन", "ta": "சரக்கு மேலாண்மை"},
        "current_score": 60,
        "target_score": 100,
    },
    {
        "skill_name": {"en": "Digital Marketing", "hi": "डिजिटल मार्केटिंग", "ta": "டிஜிட்டல் மார்க்கெட்டிங்"},
        "current_score": 30,
        "target_score": 100,
    },
]

DEMO_SCHEMES = [
    {
        "name": "PM-AJAY Skilling Grant (Pradhan Mantri Anusuchit Jaati Abhyuday Yojana)",
        "name_hi": "पीएम-अजय कौशल विकास अनुदान योजना",
        "name_ta": "பிஎம்-அஜய் திறன் மேம்பாட்டு மானியத் திட்டம்",
        "category": "Social Justice & Skilling",
        "district": "Chennai",
        "description": "District-level skill training grant and financial support for SC beneficiaries & informal micro-entrepreneurs.",
        "description_hi": "अनुसूचित जाति के लाभार्थियों और अनौपचारिक सूक्ष्म उद्यमियों के लिए जिला स्तरीय कौशल प्रशिक्षण अनुदान।",
        "description_ta": "பட்டியலின பயனாளிகள் மற்றும் முறைசாரா சிறு தொழில் முனைவோருக்கான மாவட்ட அளவிலான திறன் பயிற்சி மானியம்.",
        "eligibility": "District resident, SC beneficiary or informal micro-entrepreneur",
        "eligibility_hi": "जिला निवासी, अनुसूचित जाति के लाभार्थी या अनौपचारिक सूक्ष्म-उद्यमी",
        "eligibility_ta": "மாவட்டத்தில் வசிப்பவர், பட்டியலின பயனாளி அல்லது முறைசாரா சிறு தொழிலாளி",
        "duration": "3-6 months",
        "benefits": "Free skill certification, toolkit stipend, and direct credit linkage up to Rs 50,000",
        "benefits_hi": "मुफ्त कौशल प्रमाणन, टूलकिट वजीफा, और 50,000 रुपये तक की प्रत्यक्ष क्रेडिट लिंकेज",
        "benefits_ta": "இலவச திறன் சான்றிதழ், கருவித்தொகுப்பு உதவித்தொகை, மற்றும் 50,000 வரை கடன் இணைப்பு",
        "match_score": 96,
        "is_demo": True,
    },
    {
        "name": "PM Formalization of Micro Food Processing Enterprises (PM FME)",
        "name_hi": "प्रधानमंत्री सूक्ष्म खाद्य उद्यम औपचारिकीकरण योजना (पीएम एफएमई)",
        "name_ta": "சிறு உணவு பதப்படுத்தல் நிறுவனங்கள் முறைசார் திட்டம் (PM FME)",
        "category": "Food & Beverages",
        "district": "Chennai",
        "description": "Financial, technical, and business support for micro food processing enterprises to formalize and grow.",
        "description_hi": "सूक्ष्म खाद्य प्रसंस्करण उद्यमों को औपचारिक बनाने और बढ़ाने के लिए वित्तीय, तकनीकी और व्यावसायिक सहायता।",
        "description_ta": "சிறு உணவு பதப்படுத்தல் நிறுவனங்களை முறைப்படுத்தவும் வளர்க்கவும் நிதி, தொழில்நுட்ப மற்றும் வணிக ஆதரவு.",
        "eligibility": "Existing micro food processing unit, own or leased premises",
        "eligibility_hi": "मौजूदा सूक्ष्म खाद्य प्रसंस्करण इकाई, स्वयं या पट्टे पर लिया गया परिसर",
        "eligibility_ta": "தற்போது இயங்கும் சிறு உணவு பதப்படுத்தல் அலகு, சொந்த அல்லது குத்தகை வளாகம்",
        "duration": "Ongoing",
        "benefits": "Up to Rs 10 lakh credit linked subsidy, technical training, branding support",
        "benefits_hi": "10 लाख रुपये तक क्रेडिट लिंक्ड सब्सिडी, तकनीकी प्रशिक्षण, ब्रांडिंग सहायता",
        "benefits_ta": "10 லட்சம் வரை கடன் சார்ந்த மானியம், தொழில்நுட்ப பயிற்சி, பிராண்டிங் ஆதரவு",
        "match_score": 92,
        "is_demo": True,
    },
    {
        "name": "MUDRA Loan — Shishu Category",
        "name_hi": "मुद्रा ऋण — शिशु श्रेणी",
        "name_ta": "முத்ரா கடன் — சிசு பிரிவு",
        "category": "Finance",
        "district": "Chennai",
        "description": "Collateral-free business loans up to Rs 50,000 for micro enterprises in their early stage.",
        "description_hi": "प्रारंभिक चरण के सूक्ष्म उद्यमों के लिए 50,000 रुपये तक का संपार्श्विक-मुक्त व्यापार ऋण।",
        "description_ta": "ஆரம்ப கட்ட சிறு நிறுவனங்களுக்கு 50,000 வரை பிணை இல்லாத வணிக கடன்.",
        "eligibility": "Non-farm income generating activity, Indian citizen, no previous default",
        "eligibility_hi": "गैर-कृषि आय उत्पन्न करने वाली गतिविधि, भारतीय नागरिक, पूर्व चूक नहीं",
        "eligibility_ta": "விவசாயமற்ற வருமான ஈட்டும் செயல்பாடு, இந்திய குடிமகன், முந்தைய தவறு இல்லை",
        "duration": "1-5 years repayment",
        "benefits": "Up to Rs 50,000 loan, no collateral required, low interest",
        "benefits_hi": "50,000 रुपये तक ऋण, कोई संपार्श्विक नहीं, कम ब्याज",
        "benefits_ta": "50,000 வரை கடன், பிணை தேவையில்லை, குறைந்த வட்டி",
        "match_score": 85,
        "is_demo": True,
    },
    {
        "name": "PM Vishwakarma Toolkit and Enterprise Support",
        "name_hi": "पीएम विश्वकर्मा टूलकिट और उद्यम सहायता",
        "name_ta": "பிஎம் விஸ்வகர்மா கருவித்தொகுப்பு மற்றும் தொழில் ஆதரவு",
        "category": "Technical & Professional Skills",
        "district": "Coimbatore",
        "description": "Training, toolkit support, and affordable credit for skilled artisans and local service providers.",
        "description_hi": "कुशल कारीगरों और स्थानीय सेवा प्रदाताओं के लिए प्रशिक्षण, टूलकिट सहायता और सस्ता ऋण।",
        "description_ta": "திறமையான கைவினைஞர்கள் மற்றும் உள்ளூர் சேவை வழங்குநர்களுக்கான பயிற்சி, கருவித்தொகுப்பு மற்றும் குறைந்த வட்டி கடன்.",
        "eligibility": "Registered artisan or service provider",
        "eligibility_hi": "पंजीकृत कारीगर या सेवा प्रदाता",
        "eligibility_ta": "பதிவு செய்யப்பட்ட கைவினைஞர் அல்லது சேவை வழங்குநர்",
        "duration": "1-3 years",
        "benefits": "Toolkit incentive, skill training, and digital transaction support",
        "benefits_hi": "टूलकिट प्रोत्साहन, कौशल प्रशिक्षण और डिजिटल लेनदेन सहायता",
        "benefits_ta": "கருவித்தொகுப்பு ஊக்கத்தொகை, திறன் பயிற்சி மற்றும் டிஜிட்டல் பரிவர்த்தனை ஆதரவு",
        "match_score": 90,
        "is_demo": True,
    },
    {
        "name": "Tamil Nadu Women Entrepreneur Growth Fund",
        "name_hi": "तमिलनाडु महिला उद्यमी विकास निधि",
        "name_ta": "தமிழ்நாடு பெண்கள் தொழில்முனைவோர் வளர்ச்சி நிதி",
        "category": "Finance",
        "district": "Madurai",
        "description": "Business finance and mentoring for women starting or expanding a local enterprise.",
        "description_hi": "स्थानीय उद्यम शुरू करने या बढ़ाने वाली महिलाओं के लिए व्यापार वित्त और मार्गदर्शन।",
        "description_ta": "உள்ளூர் தொழிலை தொடங்க அல்லது விரிவுபடுத்தும் பெண்களுக்கான வணிக நிதி மற்றும் வழிகாட்டுதல்.",
        "eligibility": "Women entrepreneurs residing in Tamil Nadu",
        "eligibility_hi": "तमिलनाडु की निवासी महिला उद्यमी",
        "eligibility_ta": "தமிழ்நாட்டில் வசிக்கும் பெண் தொழில்முனைவோர்",
        "duration": "Ongoing",
        "benefits": "Working capital support, mentoring, and market linkage",
        "benefits_hi": "कार्यशील पूंजी, मार्गदर्शन और बाजार संपर्क",
        "benefits_ta": "செயல்பாட்டு மூலதனம், வழிகாட்டுதல் மற்றும் சந்தை இணைப்பு",
        "match_score": 88,
        "is_demo": True,
    },
    {
        "name": "Naan Mudhalvan Digital Skills Training",
        "name_hi": "नान मुधलवन डिजिटल कौशल प्रशिक्षण",
        "name_ta": "நான் முதல்வன் டிஜிட்டல் திறன் பயிற்சி",
        "category": "Training",
        "district": "Chennai",
        "description": "Short digital and employability courses matched to existing practical skills.",
        "description_hi": "मौजूदा व्यावहारिक कौशल से जुड़े छोटे डिजिटल और रोजगार पाठ्यक्रम।",
        "description_ta": "தற்போதைய நடைமுறை திறன்களுக்கு ஏற்ற குறுகிய டிஜிட்டல் மற்றும் வேலைவாய்ப்பு பயிற்சிகள்.",
        "eligibility": "Tamil Nadu resident seeking skill development",
        "eligibility_hi": "कौशल विकास चाहने वाला तमिलनाडु निवासी",
        "eligibility_ta": "திறன் மேம்பாட்டை விரும்பும் தமிழ்நாடு குடியிருப்பாளர்",
        "duration": "2-6 months",
        "benefits": "Free courses, certificates, and placement support",
        "benefits_hi": "मुफ्त पाठ्यक्रम, प्रमाणपत्र और रोजगार सहायता",
        "benefits_ta": "இலவச பாடநெறிகள், சான்றிதழ்கள் மற்றும் வேலைவாய்ப்பு ஆதரவு",
        "match_score": 83,
        "is_demo": True,
    },
    {
        "name": "Tamil Nadu Micro Food Enterprise Branding Grant",
        "name_hi": "तमिलनाडु सूक्ष्म खाद्य उद्यम ब्रांडिंग अनुदान",
        "name_ta": "தமிழ்நாடு சிறு உணவு நிறுவன பிராண்டிங் மானியம்",
        "category": "Food Production",
        "district": "Salem",
        "description": "Packaging, labeling, branding, and market access support for homemade food businesses.",
        "description_hi": "घरेलू खाद्य व्यवसायों के लिए पैकेजिंग, लेबलिंग, ब्रांडिंग और बाजार सहायता।",
        "description_ta": "வீட்டு உணவு தொழில்களுக்கு பேக்கேஜிங், லேபிளிங், பிராண்டிங் மற்றும் சந்தை ஆதரவு.",
        "eligibility": "Food producer or home-based food entrepreneur",
        "eligibility_hi": "खाद्य निर्माता या घरेलू खाद्य उद्यमी",
        "eligibility_ta": "உணவு தயாரிப்பாளர் அல்லது வீட்டு உணவு தொழில்முனைவோர்",
        "duration": "6-12 months",
        "benefits": "Brand identity, packaging support, and retail market linkage",
        "benefits_hi": "ब्रांड पहचान, पैकेजिंग सहायता और खुदरा बाजार संपर्क",
        "benefits_ta": "பிராண்ட் அடையாளம், பேக்கேஜிங் ஆதரவு மற்றும் சில்லறை சந்தை இணைப்பு",
        "match_score": 91,
        "is_demo": True,
    },
    {
        "name": "Retail Inventory and Digital Billing Accelerator",
        "name_hi": "रिटेल इन्वेंटरी और डिजिटल बिलिंग सहायता",
        "name_ta": "சில்லறை சரக்கு மற்றும் டிஜிட்டல் பில்லிங் உதவி",
        "category": "Business Management",
        "district": "Trichy",
        "description": "Training and subsidized tools for stock tracking, digital billing, and customer management.",
        "description_hi": "स्टॉक ट्रैकिंग, डिजिटल बिलिंग और ग्राहक प्रबंधन के लिए प्रशिक्षण और सहायता।",
        "description_ta": "சரக்கு கண்காணிப்பு, டிஜிட்டல் பில்லிங் மற்றும் வாடிக்கையாளர் மேலாண்மைக்கான பயிற்சி மற்றும் கருவிகள்.",
        "eligibility": "Small shop owner or informal retailer",
        "eligibility_hi": "छोटी दुकान का मालिक या अनौपचारिक खुदरा विक्रेता",
        "eligibility_ta": "சிறு கடை உரிமையாளர் அல்லது முறைசாரா சில்லறை விற்பனையாளர்",
        "duration": "1-3 months",
        "benefits": "Inventory software training, billing tools, and business mentoring",
        "benefits_hi": "इन्वेंटरी सॉफ्टवेयर प्रशिक्षण, बिलिंग उपकरण और व्यापार मार्गदर्शन",
        "benefits_ta": "சரக்கு மென்பொருள் பயிற்சி, பில்லிங் கருவிகள் மற்றும் வணிக வழிகாட்டுதல்",
        "match_score": 86,
        "is_demo": True,
    },
    {
        "name": "Skill India Food Safety Certification",
        "name_hi": "स्किल इंडिया खाद्य सुरक्षा प्रमाणन",
        "name_ta": "ஸ்கில் இந்தியா உணவு பாதுகாப்பு சான்றிதழ்",
        "category": "Training",
        "district": "Madurai",
        "description": "Practical food safety, hygiene, and quality certification for food producers and caterers.",
        "description_hi": "खाद्य निर्माताओं और कैटरर्स के लिए खाद्य सुरक्षा, स्वच्छता और गुणवत्ता प्रमाणन।",
        "description_ta": "உணவு தயாரிப்பாளர்கள் மற்றும் கேட்டரிங் தொழிலாளர்களுக்கான உணவு பாதுகாப்பு, சுகாதாரம் மற்றும் தரச் சான்றிதழ்.",
        "eligibility": "Food producer, baker, caterer, or kitchen worker",
        "eligibility_hi": "खाद्य निर्माता, बेकर, कैटरर या रसोई कर्मचारी",
        "eligibility_ta": "உணவு தயாரிப்பாளர், பேக்கர், கேட்டரர் அல்லது சமையலறை பணியாளர்",
        "duration": "1-2 months",
        "benefits": "Certification, hygiene toolkit, and inspection readiness support",
        "benefits_hi": "प्रमाणन, स्वच्छता टूलकिट और निरीक्षण तैयारी सहायता",
        "benefits_ta": "சான்றிதழ், சுகாதார கருவித்தொகுப்பு மற்றும் ஆய்வு தயாரிப்பு ஆதரவு",
        "match_score": 89,
        "is_demo": True,
    },
]

DEMO_PROGRESSION_STEPS = {
    "en": [
        {
            "step": 1,
            "title": "Skill Training",
            "description": "Digital Marketing for Small Business — 3 months program",
            "duration": "3 months",
            "status": "current",
            "unlocks": "PM FME application eligibility",
        },
        {
            "step": 2,
            "title": "Certification",
            "description": "Food Safety & Quality Certification from FSSAI",
            "duration": "6 months",
            "status": "upcoming",
            "unlocks": "Market access and export opportunities",
        },
        {
            "step": 3,
            "title": "Bigger Opportunities",
            "description": "Apply for PM FME scheme, access market linkages and expand business",
            "duration": "6+ months",
            "status": "upcoming",
            "unlocks": "Loan support, branding, and market access",
        },
    ],
    "hi": [
        {
            "step": 1,
            "title": "कौशल प्रशिक्षण",
            "description": "लघु व्यवसाय के लिए डिजिटल मार्केटिंग — 3 महीने का कार्यक्रम",
            "duration": "3 महीने",
            "status": "current",
            "unlocks": "पीएम एफएमई आवेदन पात्रता",
        },
        {
            "step": 2,
            "title": "प्रमाणन",
            "description": "FSSAI से खाद्य सुरक्षा और गुणवत्ता प्रमाणन",
            "duration": "6 महीने",
            "status": "upcoming",
            "unlocks": "बाजार पहुंच और निर्यात अवसर",
        },
        {
            "step": 3,
            "title": "बड़े अवसर",
            "description": "पीएम एफएमई योजना के लिए आवेदन करें, बाजार संपर्क और व्यवसाय विस्तार",
            "duration": "6+ महीने",
            "status": "upcoming",
            "unlocks": "ऋण सहायता, ब्रांडिंग और बाजार पहुंच",
        },
    ],
    "ta": [
        {
            "step": 1,
            "title": "திறன் பயிற்சி",
            "description": "சிறு வணிகத்திற்கான டிஜிட்டல் மார்க்கெட்டிங் — 3 மாத திட்டம்",
            "duration": "3 மாதங்கள்",
            "status": "current",
            "unlocks": "PM FME விண்ணப்ப தகுதி",
        },
        {
            "step": 2,
            "title": "சான்றிதழ்",
            "description": "FSSAI மூலம் உணவு பாதுகாப்பு மற்றும் தர சான்றிதழ்",
            "duration": "6 மாதங்கள்",
            "status": "upcoming",
            "unlocks": "சந்தை அணுகல் மற்றும் ஏற்றுமதி வாய்ப்புகள்",
        },
        {
            "step": 3,
            "title": "பெரிய வாய்ப்புகள்",
            "description": "PM FME திட்டத்திற்கு விண்ணப்பிக்கவும், சந்தை இணைப்பு மற்றும் வணிக விரிவாக்கம்",
            "duration": "6+ மாதங்கள்",
            "status": "upcoming",
            "unlocks": "கடன் ஆதரவு, பிராண்டிங் மற்றும் சந்தை அணுகல்",
        },
    ],
}
